using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Spring.NET REST Client Framework 2.0.0 for .NET Standard 2.0")]
[assembly: AssemblyCompanyAttribute("http://www.springframework.net/")]
[assembly: AssemblyCopyrightAttribute("Copyright 2020 SpringSource")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("2.0.0.522")]
[assembly: AssemblyConfigurationAttribute("net-standard-2.0; 2.0.0.522; dev")]

